[package]
name = "yeyofone-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[build-dependencies]
tauri-build = { version = "=2.7.1", features = [] }

[features]
default = []
native-voip = ["dep:yeyofone-voip"]

[dependencies]
yeyofone-domain = { path = "../crates/domain" }
yeyofone-application = { path = "../crates/application" }
yeyofone-platform = { path = "../crates/platform" }
serde = { version = "=1.0.229", features = ["derive"] }
zeroize = "=1.8.2"
uuid = { version = "1", features = ["v4"] }
tauri = { version = "=2.12.1", features = ["protocol-asset"] }
yeyofone-ipc = { path = "../crates/ipc" }
serde_json = "=1.0.145"
yeyofone-voip = { path = "../crates/voip", optional = true }

reqwest = { version = "=0.13.5", default-features = false, features = ["blocking", "json", "rustls"] }

[target.'cfg(target_os = "macos")'.dependencies]
keyring = { version = "=3.6.3", features = ["apple-native"] }

[lints]
workspace = true
